services:
  - type: web
    name: finpredictor
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip cache purge
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production