services:
  - type: web
    name: finpredictor
    env: python
    buildCommand: |
      apt-get update -y
      apt-get install -y build-essential python3-dev
      python -m pip install --upgrade pip
      pip cache purge
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production